using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Runtime.Remoting.Messaging;
using System.Text;
using System.Threading.Tasks;
using System.Windows.Forms;

namespace Clinic.Global_Classes
{
    public class util
    {
        //steps to generate unique name for image to avoid name conflicts when saving images to the same folder
        //step1: generate a GUID (Globally Unique Identifier) which is a 128-bit integer that can be used to uniquely identify something
        //setp2: Create Folder if not exist
        //setp3: Replace Image name with new GUID name and save the image to the folder
        //step4: save the image path to the folder in the database to be able to retrieve it later and display the image when needed
        public static string GenerateGUID()
        {
            //create GUID for image name to avoid name conflicts
            Guid newGuid = Guid.NewGuid();

            //make Guid to string
            return newGuid.ToString();
        }

        //you'll take the folder path from the caller 
        public static bool CreateFolderIfDoesNotExist(string folderPath)
        {
            //if the folder does not exist, create it
            if (!Directory.Exists(folderPath))
            {
                try//try to create the folder
                {
                    Directory.CreateDirectory(folderPath);
                    return true;//folder created successfully
                }
                catch(Exception ex)
                {
                    MessageBox.Show("Error creating folder: " + ex.Message, "Error", MessageBoxButtons.OK, MessageBoxIcon.Error);
                    return false;//failed to create folder
                }
            }
            return true;//folder already exists
        }


        public static string ReplaceFileNameWithGUID(string originalFilePath)
        {
            string fileName = originalFilePath;
            //get file extension
            FileInfo fi = new FileInfo(fileName);
            string exte = fi.Extension;

            //generate new file name with GUID and keep the original extension
            return GenerateGUID() + exte;
        }


        public static bool CopyImageToProjectImages(ref string sourceFile)
        {
            //define the FolderDestination to save the image in the project folder
            string FolderDestination = @"C:\ClinicSystem-People-Images\";

            //check if the folder is exist 
            if (!CreateFolderIfDoesNotExist(FolderDestination))
            {
                return false;//failed to create folder, so file cannot be copied
            }

            //define the destination file path by combining the folder destination with the new file name generated by replacing the original file name with a GUID
            string FileDestination = FolderDestination + ReplaceFileNameWithGUID(sourceFile);

            //try to copy the file to the destination folder
            try
            {
                File.Copy(sourceFile, FileDestination);
            }
            catch (IOException iox)
            {
                MessageBox.Show(iox.Message, "Error", MessageBoxButtons.OK, MessageBoxIcon.Error);
                return false;
            }

            //make source file equal to the destination file to be able to save the new file path in the database
            sourceFile = FileDestination;
            return true;//file copied successfully
        }
    }
}
